### PR TITLE
Add the option to send relative paths to Perforce. It makes it easier…

### PR DESCRIPTION
**Pull request by beyondmarc**
… to work with Perforce in a Windows + Cygwin environment.

### CODE REVIEW

**Comment by nfvs** [comment]
Thanks! Can you also add a line or two to the readme file, regarding the new option?

**Comment by beyondmarc** [comment]
Sure! Done!

**Comment by nfvs** [comment]
Seems like a good idea, and I wonder if this should be the default behavior. On which OSs have you tested this change?

**Comment by beyondmarc** [comment]
I'm using a Windows 7 64bit ans Cygwin 64bit. I have the Perforce repository under a second drive: E:\depot, that under Cygwin gets translated into /cygdrive/e/depot (I'm using /cygdrive/e) as a Perforce AltRoot.

This works fine, until Perforce tries to change the file permissions under Cygwin. To solve this I use this little script:

```
#! /bin/sh
PWD=`cygpath -wa .` /cygdrive/c/Program\ Files/Perforce/p4.exe $@
```

I use this as an executable for your Vim plugin, and using the relative paths change Perforce is able to find the file in Windows and correctly change the permissions.

About being the default option, that's up to you. I'll leave the option enabled in my vimrc just in case :)

**Pull request merged**
